import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
	overlay: {
		flex: 1,
		justifyContent: "flex-end",
	},
	backdrop: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0, 0, 0, 0.7)",
	},
	sheet: {
		maxHeight: "94%",
		backgroundColor: colors.background,
		borderTopLeftRadius: 26,
		borderTopRightRadius: 26,
		borderWidth: 1,
		borderColor: colors.border,
		paddingTop: 8,
		overflow: "hidden",
	},
	dragHandle: {
		width: 48,
		height: 5,
		borderRadius: 99,
		backgroundColor: colors.border,
		alignSelf: "center",
		marginBottom: 8,
	},
	header: {
		paddingHorizontal: 18,
		paddingBottom: 14,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	headerTitle: {
		color: colors.text,
		fontSize: 24,
		fontWeight: "900",
	},
	closeButton: {
		width: 46,
		height: 46,
		borderRadius: 23,
		backgroundColor: colors.card,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: colors.border,
	},
	scrollContent: {
		paddingHorizontal: 18,
		paddingBottom: 18,
	},
	loadingBlock: {
		minHeight: 360,
		alignItems: "center",
		justifyContent: "center",
		gap: 10,
	},
	loadingText: {
		color: colors.secondaryText,
		fontSize: 14,
		fontWeight: "700",
	},

	creatorTopBlock: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 16,
	},
	avatarImage: {
		backgroundColor: colors.border,
	},
	initialsAvatar: {
		backgroundColor: colors.primary,
		alignItems: "center",
		justifyContent: "center",
	},
	initialsText: {
		color: colors.background,
		fontWeight: "900",
	},
	creatorMainInfo: {
		flex: 1,
		marginLeft: 12,
		gap: 4,
		minWidth: 0,
	},
	creatorNickname: {
		color: "#9A7CFF",
		fontSize: 17,
		fontWeight: "900",
	},
	creatorFullName: {
		color: colors.text,
		fontSize: 16,
		fontWeight: "900",
	},
	creatorSmallRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
	},
	creatorMetaText: {
		color: colors.secondaryText,
		fontSize: 12,
		fontWeight: "800",
		flexShrink: 1,
	},
	creatorStatsColumn: {
		width: 82,
		gap: 8,
		paddingLeft: 8,
		borderLeftWidth: 1,
		borderLeftColor: colors.border,
	},
	creatorStatItem: {
		alignItems: "center",
		gap: 2,
	},
	creatorStatValue: {
		color: colors.text,
		fontSize: 15,
		fontWeight: "900",
		textAlign: "center",
	},
	creatorStatLabel: {
		color: colors.secondaryText,
		fontSize: 9,
		lineHeight: 11,
		fontWeight: "800",
		textAlign: "center",
	},

	aboutLanguagesCard: {
		flexDirection: "row",
		backgroundColor: colors.card,
		borderRadius: 18,
		borderWidth: 1,
		borderColor: colors.border,
		padding: 14,
		marginBottom: 14,
	},
	aboutColumn: {
		flex: 1,
		paddingRight: 12,
	},
	languagesColumn: {
		flex: 1,
		paddingLeft: 12,
	},
	verticalDivider: {
		width: 1,
		backgroundColor: colors.border,
	},
	blockTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 7,
		marginBottom: 7,
	},
	blockTitle: {
		color: colors.text,
		fontSize: 16,
		fontWeight: "900",
	},
	aboutText: {
		color: colors.secondaryText,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "700",
	},
	languagesText: {
		color: colors.secondaryText,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "800",
	},

	creatorSportsList: {
		backgroundColor: colors.card,
		borderRadius: 18,
		borderWidth: 1,
		borderColor: colors.border,
		paddingVertical: 12,
		paddingHorizontal: 10,
		gap: 8,
		marginBottom: 14,
	},
	creatorSportItem: {
		alignItems: "center",
		width: 62,
	},
	creatorSportImageWrap: {
		width: 58,
		height: 58,
		borderRadius: 29,
		overflow: "hidden",
		backgroundColor: colors.background,
		borderWidth: 2,
		borderColor: colors.border,
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 6,
	},
	creatorSportImage: {
		width: "100%",
		height: "100%",
		resizeMode: "cover",
	},
	levelBadge: {
		minHeight: 22,
		borderRadius: 11,
		paddingHorizontal: 8,
		alignItems: "center",
		justifyContent: "center",
	},
	profLevelBadge: {
		backgroundColor: "#7C3AED",
	},
	amateurLevelBadge: {
		backgroundColor: "#F97316",
	},
	beginnerLevelBadge: {
		backgroundColor: "#65A30D",
	},
	defaultLevelBadge: {
		backgroundColor: colors.border,
	},
	levelText: {
		color: colors.text,
		fontSize: 10,
		fontWeight: "900",
	},

	eventCard: {
		flexDirection: "row",
		backgroundColor: colors.card,
		borderRadius: 18,
		borderWidth: 1,
		borderColor: colors.border,
		padding: 14,
		gap: 12,
		marginBottom: 14,
	},
	eventInfoSide: {
		flex: 1,
		minWidth: 0,
	},
	eventTitle: {
		color: colors.text,
		fontSize: 20,
		fontWeight: "900",
		marginBottom: 12,
	},
	eventInfoRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginBottom: 9,
	},
	eventInfoText: {
		flex: 1,
		color: colors.secondaryText,
		fontSize: 13,
		fontWeight: "800",
	},
	eventDescription: {
		color: colors.text,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: "800",
		marginTop: 10,
	},
	eventImageSide: {
		width: 118,
		justifyContent: "center",
	},
	eventImage: {
		width: "100%",
		height: 118,
		borderRadius: 16,
		resizeMode: "cover",
		backgroundColor: colors.border,
	},
	eventImageFallback: {
		width: "100%",
		height: 118,
		borderRadius: 16,
		backgroundColor: colors.background,
		alignItems: "center",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: colors.border,
	},

	joinedSection: {
		backgroundColor: colors.card,
		borderRadius: 18,
		borderWidth: 1,
		borderColor: colors.border,
		padding: 14,
		marginBottom: 14,
	},
	joinedTitle: {
		color: colors.text,
		fontSize: 22,
		fontWeight: "900",
		marginBottom: 12,
	},
	emptyText: {
		color: colors.secondaryText,
		fontSize: 13,
		fontWeight: "700",
	},
	memberCard: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: colors.background,
		borderRadius: 16,
		padding: 10,
		borderWidth: 1,
		borderColor: colors.border,
		marginBottom: 8,
	},
	memberInfo: {
		flex: 1,
		marginLeft: 10,
	},
	memberName: {
		color: "#9A7CFF",
		fontSize: 15,
		fontWeight: "900",
	},
	memberRating: {
		color: colors.secondaryText,
		fontSize: 12,
		fontWeight: "700",
		marginTop: 2,
	},

	actions: {
		padding: 18,
		borderTopWidth: 1,
		borderTopColor: colors.border,
		backgroundColor: colors.background,
	},
	joinButton: {
		height: 54,
		borderRadius: 18,
		backgroundColor: colors.primary,
		alignItems: "center",
		justifyContent: "center",
	},
	disabledButton: {
		opacity: 0.65,
	},
	joinButtonText: {
		color: colors.background,
		fontSize: 16,
		fontWeight: "900",
	},
	secondaryActions: {
		flexDirection: "row",
		gap: 12,
		marginTop: 12,
	},
	secondaryButton: {
		flex: 1,
		height: 48,
		borderRadius: 16,
		backgroundColor: colors.card,
		borderWidth: 1,
		borderColor: colors.border,
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: 8,
	},
	secondaryButtonText: {
		color: colors.text,
		fontSize: 15,
		fontWeight: "900",
	},
	buttonPressed: {
		opacity: 0.75,
		transform: [{ scale: 0.98 }],
	},
});
